[project]
name = "lib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "sphinx-rtd-theme>=3.0.2",
    "sphinx>=8.1.3",
]
